---

name: myFirstWorkflow
on: workflow_dispatch

jobs:
  aProfileBuild:
    runs-on: ubuntu-latest
    steps:
      - name: cloneRepository
        uses: actions/checkout@v4

      - name: mavenTest
        run: mvn test

      - name: checkStyleAnalysis
        run: mvn checkstyle:checkstyle
